name: tlsplugin
version: "3.15.3"
main: com.tlsplugin.Tlsplugin
api-version: "1.21"
author: "ArrozNaTwitch"
depend: [ ItemsAdder, ProtocolLib, packetevents ]
softdepend: [ LuckPerms ]
commands:
  setborda:
    description: "Define a borda inicial para o valor configurado (ex: 10000)."
    usage: /setborda
    permission: tls.admin
  startgame:
    description: "Inicia o ciclo de bordas (start game)."
    usage: /startgame
    permission: tls.admin
  teamjoin:
    description: Junta-se a uma equipe e dá o grupo correspondente.
    usage: /<command> <team> [player]
    permission: tls.admin
  tlsreload:
    description: Recarrega o config
    permission: tls.admin
  endgame:
    description: Termina o jogo
    permission: tls.admin
  pause:
    description: Pausa/retoma o jogo
    permission: tls.admin
  unpause:
    description: remota o jogo
    permission: tls.admin
  pedirpausa:
    description: Pede uma pausa ao jogo (por jogador)
    usage: /pedirpausa [motivo]
  aceitarpausa:
    description: Aceita um pedido de pausa de um jogador (só OP)
    usage: /aceitarpausa <nick>
    permission: tls.admin
  allteamscreate:
    description: Cria todos os times do scoreboard
    permission: tls.admin
  mvp:
    description: Mostra o ranking MVP (Top 10 por pontos)
    usage: /mvp
    permission: tls.admin
  sobremvp:
    description: Mostra as estatísticas detalhadas de um jogador
    usage: /sobremvp <nick>
    permission: tls.admin
  craftbook:
    description: Abre o Livro de Receitas
    usage: /craftbook
  pronto:
    description: Marca/desmarca o jogador como pronto (visível apenas aos OPs)
    usage: /pronto
  anunciar:
    description: Envia um anúncio em destaque para todos os jogadores
    usage: /anunciar <mensagem>
    permission: tls.admin
  tlsconfig:
    description: Abre a GUI de configuração do plugin
    usage: /tlsconfig
    permission: tls.admin
  tlsworld:
    description: Define o mundo onde o TLS opera
    usage: /tlsworld [nomeMundo]
    permission: tls.admin
  tls:
    description: Gestão de spawns de equipas
    usage: /tls <setspawn|tp|spawns|delspawn> [args]
    permission: tls.admin pe
  tlspawn:
    description: Teleporta para o spawn da tua equipa
    usage: /tlspawn
  tlssign:
    description: Gestão de placas interativas com permissão
    usage: /tlssign <cor|set|remove|list|info> [args]
    permission: tls.admin
  tlscapsulas:
    description: "Gera cápsulas 3x3 para todas as equipas, com spawn e placa automáticos."
    usage: /tlscapsulas <world> [x y z]
    permission: tls.admin
  tlsteams:
    description: Dá os 8 blocos de lã para escolha de equipa
    usage: /tlsteams
    permission: tls.admin
  scoreboard:
    description: Toggle da scoreboard
